services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AlipayFundAuthBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  AlipayFundAuthBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'

  AlipayFundAuthBundle\Procedure\:
    resource: '../../Procedure/'

  AlipayFundAuthBundle\Repository\:
    resource: '../../Repository/'

  AlipayFundAuthBundle\Service\:
    resource: '../../Service/'
    public: true
